version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: haruspeak-api
      MYSQL_USER: haruspeak
      MYSQL_PASSWORD: haruspeak
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      ai:
        condition: service_started

  ai:
    build:
      context: ./ai/app
      dockerfile: Dockerfile
    container_name: ai-server
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: